<a href="https://colab.research.google.com/github/2017130715/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%matplotlib inline
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

In [18]:
def phaser(amp, sr, dur, freq):
  t = np.arange(amp, sr * dur+1)/sr
  theta = t * 2*np.pi * freq
  s = np.sin(theta)
  return s, theta, t

In [22]:
phaser(2, 20000, 1, 400)

(array([ 2.48689887e-01,  3.68124553e-01,  4.81753674e-01, ...,
        -2.48689887e-01, -1.25333234e-01,  1.57150938e-14]),
 array([2.51327412e-01, 3.76991118e-01, 5.02654825e-01, ...,
        2.51302280e+03, 2.51314846e+03, 2.51327412e+03]),
 array([1.0000e-04, 1.5000e-04, 2.0000e-04, ..., 9.9990e-01, 9.9995e-01,
        1.0000e+00]))